language: node_js
node_js:
  - "14"  # Use a stable version or specify the exact version
dist: xenial  # Or bionic if necessary
cache:
  directories:
    - node_modules
install:
  - npm install  # Install dependencies without additional npm config commands
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
