language: node_js
node_js:
  - "14"
branches:
  only:
    - master  # This specifies that only the 'main' branch triggers a deployment.

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn  # Added yarn installation as it may be beneficial for faster builds.

script:
  #- yarn lint
  - yarn build
  - mv build/index.html build/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

